/* pwd : 1234 */
insert into member (email, id, name, phone, pwd, role) values ("test01@test.com", "test01", "테스터01", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test02@test.com", "test02", "테스터02", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test03@test.com", "test03", "테스터03", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test04@test.com", "test04", "테스터04", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test05@test.com", "test05", "테스터05", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test06@test.com", "test06", "테스터06", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test07@test.com", "test07", "테스터07", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test08@test.com", "test08", "테스터08", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test09@test.com", "test09", "테스터09", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test10@test.com", "test10", "테스터10", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test11@test.com", "test11", "테스터11", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test12@test.com", "test12", "테스터12", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test13@test.com", "test13", "테스터13", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test14@test.com", "test14", "테스터14", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test15@test.com", "test15", "테스터15", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test16@test.com", "test16", "테스터16", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test17@test.com", "test17", "테스터17", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test18@test.com", "test18", "테스터18", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test19@test.com", "test19", "테스터19", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test20@test.com", "test20", "테스터20", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("admin@claco.com", "admin", "관리자", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_ADMIN");
commit;

insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST1", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST2", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST3", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST4", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST5", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST6", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST7", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST8", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST9", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST10", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST11", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST12", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST13", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST14", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST15", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST16", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST17", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST18", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST19", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST20", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST21", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST22", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST23", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST24", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST25", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST26", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST27", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST28", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST29", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST30", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST31", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST32", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST33", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST34", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST35", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST36", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST37", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST38", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST39", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "TEST", "TEST40", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today1", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today2", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today3", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today4", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today5", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today6", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today7", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today8", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today9", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today10", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today11", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today12", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today13", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today14", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today15", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today16", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today17", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today18", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today19", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today20", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today21", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today22", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today23", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today24", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today25", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today26", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today27", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today28", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today29", "test01", 1);
insert into freeboard (created_date, modified_date, contents, title, writer, mindex) values (NOW(), NOW(), "Table", "Today30", "test01", 1);

insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 1번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 2번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 3번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 4번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 5번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 6번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 7번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 8번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 9번입니다.", "admin");
insert into alertboard (created_date, modified_date, contents, title, writer) values (NOW(), NOW(), "공지사항테스트", "공지사항 10번입니다.", "admin");

insert into academy (address, companynum, grade, location, name, mindex) values ("서울시 강남구", "111-22-33333", 999, "강남구", "테스트학원1", 11);
insert into academy (address, companynum, grade, location, name, mindex) values ("부산시 사상구", "111-22-33333", 1000, "사상구", "테스트학원2", 12);
insert into academy (address, companynum, grade, location, name, mindex) values ("서울시 강서구", "111-22-33333", 1999, "강서구", "테스트학원3", 13);
insert into academy (address, companynum, grade, location, name, mindex) values ("부산시 사하구", "111-22-33333", 2000, "사하구", "테스트학원4", 14);
insert into academy (address, companynum, grade, location, name, mindex) values ("서울시 강남구", "111-22-33333", 2999, "강남구", "테스트학원5", 15);
insert into academy (address, companynum, grade, location, name, mindex) values ("부산시 사상구", "111-22-33333", 3000, "사상구", "테스트학원6", 16);
insert into academy (address, companynum, grade, location, name, mindex) values ("서울시 강서구", "111-22-33333", 3999, "강서구", "테스트학원7", 17);
insert into academy (address, companynum, grade, location, name, mindex) values ("부산시 사하구", "111-22-33333", 4000, "사하구", "테스트학원8", 18);
insert into academy (address, companynum, grade, location, name, mindex) values ("서울시 강남구", "111-22-33333", 0, "강남구", "테스트학원9", 19);
insert into academy (address, companynum, grade, location, name, mindex) values ("부산시 사상구", "111-22-33333", 1200, "사상구", "테스트학원10", 20);

insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("프로그래밍", NOW(), NOW(), "Java Web Programming", 1234000, 3.5, "approval", 1, 1);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("요리", NOW(), NOW(), "초보도 하는 요리", 555000, 4.8, "approval", 1, 2);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("음악", NOW(), NOW(), "노래 잘 부르는 방법", 1000000, 4.3, "approval", 1, 3);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("요리", NOW(), NOW(), "영국 요리 따라만들기", 998000, 2.8, "approval", 1, 4);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("음악", NOW(), NOW(), "입으로 기타소리 내는 방법", 585000, 3.7, "approval", 1, 5);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("프로그래밍", NOW(), NOW(), "C++ Programming", 777000, 3.1, "approval", 1, 6);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("프로그래밍", NOW(), NOW(), "옆 학원보다 잘 가르치는 Phyton", 2320000, 1.9, "approval", 1, 7);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("프로그래밍", NOW(), NOW(), "안드로이드 앱 개발자가 되자", 900000, 3.7, "approval", 1, 8);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("음악", NOW(), NOW(), "집에서 쉽게 따라하는 피아노 연주", 1234000, 4.2, "approval", 1, 9);
insert into class (category, startperiod, endperiod, name, price, score, status, iindex, aindex) values ("요리", NOW(), NOW(), "동양의 요리 연구", 350000, 4.9, "approval", 1, 10);

insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "1");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "1");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "2");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "4");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "9");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "5");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "8");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "6");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "3");
insert into comments (created_date, modified_date, comment, bindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "12");

insert into imagefile (name, path) values ("사진1", "classpath:/static/img");
insert into imagefile (name, path) values ("사진2", "classpath:/static/img");

insert into review(created_date, modified_date, contents, score, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 1", 4.1, 1, 1);
insert into review(created_date, modified_date, contents, score, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 2", 2.8, 1, 1);
insert into review(created_date, modified_date, contents, score, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 3", 3.7, 2, 2);
insert into review(created_date, modified_date, contents, score, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 4", 2.2, 3, 3);
insert into review(created_date, modified_date, contents, score, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 5", 3.4, 4, 4);

commit;