/* pwd : 1234 */
insert into member (email, id, name, phone, pwd, role) values ("test01@test.com", "test01", "테스터01", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test02@test.com", "test02", "테스터02", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test03@test.com", "test03", "테스터03", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test04@test.com", "test04", "테스터04", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test05@test.com", "test05", "테스터05", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test06@test.com", "test06", "테스터06", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test07@test.com", "test07", "테스터07", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test08@test.com", "test08", "테스터08", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test09@test.com", "test09", "테스터09", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test10@test.com", "test10", "테스터10", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_MEMBER");
insert into member (email, id, name, phone, pwd, role) values ("test11@test.com", "test11", "테스터11", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test12@test.com", "test12", "테스터12", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test13@test.com", "test13", "테스터13", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test14@test.com", "test14", "테스터14", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test15@test.com", "test15", "테스터15", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test16@test.com", "test16", "테스터16", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test17@test.com", "test17", "테스터17", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test18@test.com", "test18", "테스터18", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test19@test.com", "test19", "테스터19", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("test20@test.com", "test20", "테스터20", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_COMPANY");
insert into member (email, id, name, phone, pwd, role) values ("admin@claco.com", "admin", "관리자", "010-1234-5678", "$2a$10$q6aahSYucIp1Fnbf5zzoYuzYdN5r4pkigvWpz7nJcnBPCzVeAqddW", "ROLE_ADMIN");
commit;

insert into academy (address, companynum, grade, location, name, info, mindex) values ("서울시 강남구", "111-22-33333", 999, "강남구", "테스트학원1", "테스트학원1 소개입니다.", 11);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("부산시 사상구", "111-22-33333", 1000, "사상구", "테스트학원2", "테스트학원2 소개입니다.", 12);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("서울시 강서구", "111-22-33333", 1999, "강서구", "테스트학원3", "테스트학원3 소개입니다.", 13);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("부산시 사하구", "111-22-33333", 2000, "사하구", "테스트학원4", "테스트학원4 소개입니다.", 14);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("서울시 강남구", "111-22-33333", 2999, "강남구", "테스트학원5", "테스트학원5 소개입니다.", 15);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("부산시 사상구", "111-22-33333", 3000, "사상구", "테스트학원6", "테스트학원6 소개입니다.", 16);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("서울시 강서구", "111-22-33333", 3999, "강서구", "테스트학원7", "테스트학원7 소개입니다.", 17);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("부산시 사하구", "111-22-33333", 4000, "사하구", "테스트학원8", "테스트학원8 소개입니다.", 18);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("서울시 강남구", "111-22-33333", 0, "강남구", "테스트학원9", "테스트학원9 소개입니다.", 19);
insert into academy (address, companynum, grade, location, name, info, mindex) values ("부산시 사상구", "111-22-33333", 1200, "사상구", "테스트학원10", "테스트학원10 소개입니다.", 20);

insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST1", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST2", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST3", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST4", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST5", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST6", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST7", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST8", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST9", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST10", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST11", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST12", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST13", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST14", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST15", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST16", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST17", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST18", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST19", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST20", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST21", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST22", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST23", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST24", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST25", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST26", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST27", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST28", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST29", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST30", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST31", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST32", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST33", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST34", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST35", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST36", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST37", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST38", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST39", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "TEST", "TEST40", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today1", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today2", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today3", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today4", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today5", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today6", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today7", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today8", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today9", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today10", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today11", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today12", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today13", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today14", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today15", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today16", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today17", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today18", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today19", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today20", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today21", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today22", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today23", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today24", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today25", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today26", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today27", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today28", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today29", 1);
insert into freeboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "Table", "Today30", 1);

insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 1번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 2번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 3번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 4번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 5번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 6번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 7번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 8번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 9번입니다.", 21);
insert into alertboard (created_date, modified_date, contents, title, mindex) values (NOW(), NOW(), "공지사항테스트", "공지사항 10번입니다.", 21);

insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("프로그래밍", NOW(), NOW(), "Java Web Programming", 1234000, 3.5, "approval", "강의1의 소개입니다.", 1);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("요리", NOW(), NOW(), "초보도 하는 요리", 555000, 4.8, "approval", "강의2의 소개입니다.", 2);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("음악", NOW(), NOW(), "노래 잘 부르는 방법", 1000000, 4.3, "approval", "강의3의 소개입니다.", 3);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("요리", NOW(), NOW(), "영국 요리 따라만들기", 998000, 2.8, "approval", "강의4의 소개입니다.", 4);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("음악", NOW(), NOW(), "입으로 기타소리 내는 방법", 585000, 3.7, "approval", "강의5의 소개입니다.", 5);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("프로그래밍", NOW(), NOW(), "C++ Programming", 777000, 3.1, "approval", "강의6의 소개입니다.", 6);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("프로그래밍", NOW(), NOW(), "옆 학원보다 잘 가르치는 Phyton", 2320000, 1.9, "approval", "강의7의 소개입니다.", 7);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("프로그래밍", NOW(), NOW(), "안드로이드 앱 개발자가 되자", 900000, 3.7, "approval", "강의8의 소개입니다.", 8);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("음악", NOW(), NOW(), "집에서 쉽게 따라하는 피아노 연주", 1234000, 4.2, "approval", "강의9의 소개입니다.", 9);
insert into class (category, startperiod, endperiod, name, price, score, status, info, aindex) values ("요리", NOW(), NOW(), "동양의 요리 연구", 350000, 4.9, "approval", "강의10의 소개입니다.", 10);

insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "1");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "1");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "2");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "4");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "9");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "5");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "8");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "6");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "3");
insert into comments (created_date, modified_date, comment, fbindex, mindex) values (NOW(), NOW(), "테스트용 댓글", "70", "12");

insert into academyimage (name, path, aindex) values ("사진1", "classpath:/static/img/", 1);
insert into academyimage (name, path, aindex) values ("사진2", "classpath:/static/img/", 2);
insert into academyimage (name, path, aindex) values ("사진1", "classpath:/static/img/", 3);
insert into academyimage (name, path, aindex) values ("사진2", "classpath:/static/img/", 4);
insert into academyimage (name, path, aindex) values ("사진1", "classpath:/static/img/", 5);
insert into academyimage (name, path, aindex) values ("사진2", "classpath:/static/img/", 6);
insert into academyimage (name, path, aindex) values ("사진1", "classpath:/static/img/", 7);
insert into academyimage (name, path, aindex) values ("사진2", "classpath:/static/img/", 8);
insert into academyimage (name, path, aindex) values ("사진1", "classpath:/static/img/", 9);
insert into academyimage (name, path, aindex) values ("사진2", "classpath:/static/img/", 10);

insert into classimage (name, path, cindex) values ("사진1", "classpath:/static/img/", 1);
insert into classimage (name, path, cindex) values ("사진2", "classpath:/static/img/", 2);
insert into classimage (name, path, cindex) values ("사진1", "classpath:/static/img/", 3);
insert into classimage (name, path, cindex) values ("사진2", "classpath:/static/img/", 4);
insert into classimage (name, path, cindex) values ("사진1", "classpath:/static/img/", 5);
insert into classimage (name, path, cindex) values ("사진2", "classpath:/static/img/", 6);
insert into classimage (name, path, cindex) values ("사진1", "classpath:/static/img/", 7);
insert into classimage (name, path, cindex) values ("사진2", "classpath:/static/img/", 8);
insert into classimage (name, path, cindex) values ("사진1", "classpath:/static/img/", 9);
insert into classimage (name, path, cindex) values ("사진2", "classpath:/static/img/", 10);

/*
insert into freeboardimage (name, path, fbindex) values ("사진1", "classpath:/static/img/", 1);
insert into freeboardimage (name, path, fbindex) values ("사진2", "classpath:/static/img/", 2);
insert into freeboardimage (name, path, fbindex) values ("사진1", "classpath:/static/img/", 3);
insert into freeboardimage (name, path, fbindex) values ("사진2", "classpath:/static/img/", 4);
insert into freeboardimage (name, path, fbindex) values ("사진1", "classpath:/static/img/", 5);
insert into freeboardimage (name, path, fbindex) values ("사진2", "classpath:/static/img/", 6);
insert into freeboardimage (name, path, fbindex) values ("사진1", "classpath:/static/img/", 7);
insert into freeboardimage (name, path, fbindex) values ("사진2", "classpath:/static/img/", 8);
insert into freeboardimage (name, path, fbindex) values ("사진1", "classpath:/static/img/", 9);
insert into freeboardimage (name, path, fbindex) values ("사진2", "classpath:/static/img/", 10);
*/

insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 1", 4.1, "approval", 1, 1);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 2", 2.8, "approval", 1, 1);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 3", 3.7, "approval", 2, 2);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 4", 2.2, "approval", 3, 3);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 5", 3.4, "approval", 4, 4);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 6", 3.4, "limited", 5, 5);
insert into review(created_date, modified_date, contents, score, status, cindex, mindex) values (NOW(), NOW(), "리뷰 테스트 7", 3.4, "limited", 6, 6);


commit;